# Generated by Django 3.0.6 on 2020-06-05 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.URLField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.URLValidator()]),
        ),
    ]
