# Generated by Django 3.0.6 on 2020-06-05 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200605_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.URLField(validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.URLValidator()], verbose_name='Длинная ссылка'),
        ),
    ]
