# Generated by Django 3.0.6 on 2020-06-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reduces', '0002_auto_20200603_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
